Repository today-they-learned/peacepiece_front, pull requests merged in 2022-08, with the labels that each got.

#20 Feat: 완료/미완료 카드 컴포넌트 생성
  .eslintrc.js
  public/images/card.png
  public/images/person.png
  src/components/Card/Card.tsx
  src/components/Challenge/Challenge.tsx
Labels: :bulb: Feature, 👏 Merge Needed

#21 Feature/15 footbar
  src/components/Footbar/DesktopFootbar.tsx
  src/components/Footbar/MobileFootbar.tsx
  src/components/Island/Island.tsx
  src/layouts/desktop.layout.js
  src/layouts/mobile.layout.js
Labels: :bulb: Feature, 👀 In review

#5 Feature/3 modal
  package.json
  public/x.png
  src/components/Modal/ModalFrame.tsx
  src/components/common/FlexButton.tsx
  yarn.lock
Labels: 👀 In review

#39 Feature/19 navbar
  src/App.tsx
  src/components/Card/Card.tsx
  src/components/Challenge/Challenge.tsx
  src/components/Challenge/EndedChallenge.tsx
  src/components/Challenge/ProposalChallenge.tsx
  src/components/Navbar/DesktopNavbar.tsx
  src/layouts/desktop.layout.js
Labels: :bulb: Feature, 👀 In review

#43 feat: banner box 한 개로 합침
  src/components/Island/Island.tsx
  src/components/common/BannerBox.tsx
  src/constants/color.js
Labels: :bulb: Feature, 👏 Merge Needed

#41 Feature/28 tooltip
  src/components/Tooltip/Tooltip.tsx
Labels: :bulb: Feature, 👏 Merge Needed

#42 feat: FlexTextBox
  src/components/common/FlexButton.tsx
  src/components/common/FlexTextBox.tsx
  yarn.lock
Labels: :bulb: Feature, 👏 Merge Needed

#44 Featuer/34_ended_challenge_layout
  src/components/Card/Card.tsx
  src/components/Card/EndedCard.tsx
  src/components/Challenge/Challenge.tsx
  src/components/Challenge/EndedChallenge.tsx
  src/components/Navbar/DesktopNavbar.tsx
Labels: :bulb: Feature, 👏 Merge Needed

#45 feat: 페이지 라우팅 추가
  src/App.tsx
  src/components/Navbar/DesktopNavbar.tsx
  src/pages/NotFound.tsx
  src/pages/index.js
Labels: :bulb: Feature, 👀 In review

#57 Feature/36 challenge title
  src/components/Card/EndedChallengeCard.tsx
  src/components/Challenge/Challenge.tsx
  src/components/Challenge/EndedChallenge.tsx
  src/components/common/ChallengeTitle.tsx
Labels: :bulb: Feature, 👀 In review

#58 Feat: 내가 해냄 아이콘 분리
  src/components/Card/EndedChallengeCard.tsx
  src/components/common/DidItIcon.tsx
Labels: :bulb: Feature, 👀 In review

#60 Feature/52 challenge figure
  src/components/Card/ChallengeCard.tsx
  src/components/Card/EndedChallengeCard.tsx
  src/components/common/ChallengeFigure.tsx
Labels: 👏 Merge Needed, 🧹 Refactor

#53 feat: toggle
  src/components/Island/Island.tsx
  src/components/Modal/ProfileModal.tsx
  src/components/common/Toggle.tsx
Labels: :bulb: Feature, 🛠 Developing, 👏 Merge Needed

#61 Feature/30 today challenge
  src/components/Card/ChallengeCard.tsx
  src/components/Card/EndedChallengeCard.tsx
  src/components/Challenge/TodayChallenge.tsx
  src/components/Navbar/DesktopNavbar.tsx
  src/pages/Challenge.tsx
  src/pages/EndedChallenge.tsx
  src/styles/GlobalStyles.js
Labels: :bulb: Feature, 👏 Merge Needed

#62 Feature/24 weekly challenge card
  src/components/Challenge/Card/ChallengeMiniCard.tsx
  src/components/Challenge/ChallengeFigure.tsx
  src/components/common/BannerBox.tsx
Labels: 👏 Merge Needed

#54 Feature/29 notic keyword
  src/components/Challenge/Card/NoticKeyword.tsx
  src/components/common/BannerBox.tsx
Labels: :bulb: Feature, 👏 Merge Needed

#78 feat: challenge offer banner
  src/App.tsx
  src/components/Challenge/Banner/OfferChallengeBanner.tsx
  src/components/Challenge/Card/NoticKeyword.tsx
  src/components/Challenge/ChallengeBanner.tsx
  src/components/Modal/ModalFrame.tsx
  src/components/common/FlexButton.tsx
  src/components/common/FlexTextBox.tsx
  src/pages/NotFound.tsx
Labels: :bulb: Feature, 👀 In review

#71 Feature/33 slider
  package.json
  src/components/Slider/Slider.tsx
  src/components/Slider/dummyData.ts
  yarn.lock
Labels: :bulb: Feature, 👏 Merge Needed

#75 Feature/69 similar challenge
  src/components/Challenge/Banner/SimilarChallengeBanner.tsx
  src/components/Challenge/Card/ChallengeMiniCard.tsx
  src/components/Challenge/SimilarChallengeList.tsx
Labels: :bulb: Feature, 👏 Merge Needed

#77 feat: react-query를 이용한 유저 로그인/회원가입
  package.json
  src/App.tsx
  src/apis/authAPI.js
  src/components/Form/Button.tsx
  src/components/Form/Field.tsx
  src/components/Sign/Login.tsx
  src/components/Sign/Signup.tsx
  src/components/Tab/TabBtn.tsx
  src/components/common/FlexBox.tsx
  src/config/api.ts
  src/constants/queryKeys.ts
  src/constants/url.ts
  src/hooks/queries/auth/index.ts
  src/hooks/queries/auth/useLogin.ts
  src/hooks/queries/auth/useSignUp.ts
  src/hooks/useInput.ts
  src/pages/Sign.tsx
  yarn.lock
Labels: :bulb: Feature, 👀 In review

#81 feat: 이런 챌린지는 어때요 배너 컴포넌트
  src/components/Challenge/Banner/CertificationBanner.tsx
  src/components/Challenge/Banner/ChallengeOfferGather.tsx
  src/components/Challenge/Card/ChallengeOfferCard.tsx
  src/components/Challenge/Card/index.ts
  src/components/Challenge/ChallengeTitle.tsx
  src/components/Challenge/TodayChallenge.tsx
  src/components/Tooltip/Tooltip.tsx
  src/pages/Challenge.tsx
Labels: :bulb: Feature

#82 Feature/65 person icon
  src/components/Challenge/ChallengeFigure.tsx
Labels: :bulb: Feature, 👀 In review

#72 feat: FlexInput
  src/components/Form/Input.tsx
Labels: :bulb: Feature, 👀 In review
