Repository today-they-learned/peacepiece_front, pull requests merged in 2022-09, with the labels that each got.

#85 Feature/67 all challenge offer
  src/components/Challenge/AllChallengeOfferList.tsx
  src/components/Challenge/Banner/AllChallengeOffer.tsx
  src/components/Challenge/ChallengeBanner.tsx
  src/components/Challenge/ChallengeTitle.tsx
  src/components/Challenge/TodayChallenge.tsx
  src/pages/ChallengeOffer.tsx
Labels: :bulb: Feature, 👀 In review

#84 feat: 챌린지 상세 컴포넌트
  public/images/image1.png
  public/images/image2.png
  public/images/image3.png
  public/images/thumbnail.png
  src/components/Challenge/Banner/ChallengeDetailBanner.tsx
  src/components/common/FlexButton.tsx
  src/pages/Challenge.tsx
Labels: :bulb: Feature, 👀 In review

#93 나의 섬 1차 리팩토링
  src/components/Island/IslandImages/beachCornerES.png
  src/components/Island/IslandImages/beachCornerSW.png
  src/components/Island/IslandImages/beachE.png
  src/components/Island/IslandImages/beachN.png
  src/components/Island/IslandImages/beachS.png
  src/components/Island/IslandImages/beachW.png
  src/components/Island/IslandViewer.jsx
  src/components/Island/TileEngine/TileMapProcessor.js
  src/components/Island/TileEngine/TileSwitcher.js
  src/components/Island/TileEngine/tileMaps.js
  src/components/Island/Tiles.css
  src/constants/Island/Maps.js
  src/pages/Island.tsx
Labels: 👀 In review

#87 Feature/31 challenge main layout
  src/components/Challenge/Banner/ChallengeOfferGather.tsx
  src/components/Challenge/Banner/EndedChallengeBanner.tsx
  src/components/Challenge/Banner/OfferChallengeBanner.tsx
  src/components/Challenge/Card/ChallengeCard.tsx
  src/components/Challenge/Card/ChallengeOfferCard.tsx
  src/components/Challenge/Card/EndedChallengeCard.tsx
  src/components/Challenge/Card/NoticKeyword.tsx
  src/components/Challenge/ChallengeFigure.tsx
  src/components/Challenge/EndedChallengeList.tsx
  src/components/Challenge/TodayChallenge.tsx
  src/components/Challenge/WeeklyChallenge.tsx
  src/components/Slider/dummyData.ts
  src/components/common/BannerBox.tsx
  src/components/common/FlexBox.tsx
  src/layouts/desktop.layout.jsx
  src/layouts/responsive.layout.jsx
  src/pages/Challenge.tsx
  src/pages/ChallengeOffer.tsx
  src/pages/EndedChallenge.tsx
  src/styles/GlobalStyles.js
Labels: :bulb: Feature, 👀 In review

#94 Feature/88 challenge testimonial
  public/images/Rectangle 85.png
  public/images/image4.png
  public/images/image5.png
  public/images/man.png
  src/components/Challenge/Banner/ChallengeTestimonial.tsx
  src/components/Challenge/Card/TestimonialCard.tsx
  src/components/Challenge/ChallengeBanner.tsx
  src/components/Challenge/ChallengeTitle.tsx
  src/components/common/FlexBox.tsx
  src/components/common/FlexTextBox.tsx
Labels: :bulb: Feature, 👀 In review

#95 Feature/90 close warning modal
  src/components/Modal/CloseWarningModal.tsx
  src/components/Modal/ModalFrame.tsx
  src/components/common/FlexBox.tsx
Labels: :bulb: Feature, 👀 In review

#104 fix: navbar 라우터에 맞게 적용
  src/components/Navbar/DesktopNavbar.tsx
Labels: :bug: Bug, 👀 In review

#109 Feature/91 챌린지 상세페이지 레이아웃
  src/App.tsx
  src/components/Challenge/Banner/CertificationBanner.tsx
  src/components/Challenge/Banner/ChallengeDetailBanner.tsx
  src/components/Challenge/Banner/ChallengeTestimonial.tsx
  src/constants/color.js
  src/pages/ChallengeDetail.tsx
  src/pages/index.js
Labels: :bulb: Feature, 👀 In review

#107 [API] article CRUD & user token validation check and refresh
  package.json
  src/App.tsx
  src/apis/articleAPI.js
  src/apis/authAPI.js
  src/components/Form/Button.tsx
  src/components/Form/ErrorText.tsx
  src/components/Form/index.js
  src/components/Sign/Login.tsx
  src/components/Sign/Signup.tsx
  src/components/common/FlexButton.tsx
  src/config/api.ts
  src/config/index.ts
  src/config/queryClient.ts
  src/constants/queryKeys.ts
  src/hooks/queries/article/index.ts
  src/hooks/queries/article/useAddArticle.ts
  src/hooks/queries/article/useArticleData.ts
  src/hooks/queries/article/useDeleteArticle.ts
  src/hooks/queries/article/useUpdateArticle.ts
  src/hooks/queries/auth/useLogin.ts
  src/hooks/queries/auth/useSignUp.ts
  src/pages/NotFound.tsx
  yarn.lock
Labels: :bulb: Feature, 👀 In review

#116 [챌린지] 챌린지 피스 Infinity scroll 구현
  package.json
  src/App.tsx
  src/components/Challenge/Banner/ChallengeDetailBanner.tsx
  src/components/Challenge/Banner/ChallengeTestimonial.tsx
  src/components/Challenge/Card/ChallengeCard.tsx
  src/components/Challenge/Card/TestimonialCard.tsx
  src/components/Challenge/EndedChallengeCardList.tsx
  src/components/Challenge/TodayChallengeList.tsx
  src/components/Tab/TabBtn.tsx
  src/components/common/BannerBox.tsx
  src/components/common/FlexBox.tsx
  src/components/common/FlexButton.tsx
  src/components/common/FlexTextBox.tsx
  src/hooks/queries/article/useArticleListData.ts
  src/hooks/queries/article/useArticleSearchData.ts
  src/hooks/queries/challenge/useChallengeArticleData.ts
  src/hooks/useDate.ts
  src/pages/EndedChallenge.tsx
  src/types/article.ts
  src/types/challenge.ts
  src/types/image.ts
  src/types/index.ts
  yarn.lock
Labels: :bulb: Feature, 👀 In review

#114 feat: 피스 글쓰기 컴포넌트
  src/components/Modal/ModalFrame.tsx
  src/components/Peace/Writing.tsx
Labels: :bulb: Feature

#118 [API] 챌린지 API 연결 / 카테고리 리마인더 autocomplete 제작
  .eslintrc.js
  package.json
  src/App.tsx
  src/apis/challengeAPI.ts
  src/components/Challenge/Banner/CertificationBanner.tsx
  src/components/Challenge/Banner/ChallengeDetailBanner.tsx
  src/components/Challenge/Banner/ChallengeTestimonial.tsx
  src/components/Challenge/TodayChallengeList.tsx
  src/components/Form/AutoComplete.tsx
  src/components/Form/index.ts
  src/components/common/FlexButton.tsx
  src/constants/queryKeys.ts
  src/hooks/index.ts
  src/hooks/queries/article/useArticleListData.ts
  src/hooks/queries/article/useArticleSearchData.ts
  src/hooks/queries/auth/useLogin.ts
  src/hooks/queries/auth/useSignUp.ts
  src/hooks/queries/challenge/index.ts
  src/hooks/queries/challenge/reminder/index.ts
  src/hooks/queries/challenge/reminder/useChallengeCategoryData.ts
  src/hooks/queries/challenge/useChallengeArticleData.ts
  src/hooks/queries/challenge/useChallengeData.ts
  src/hooks/useQueryDebounce.ts
  src/hooks/useUser.ts
  src/pages/ChallengeDetail.tsx
  src/pages/EndedChallenge.tsx
  src/pages/NotFound.tsx
  src/pages/Test.tsx
  src/pages/index.ts
  src/types/challenge.ts
  yarn.lock
Labels: :bug: Bug, :bulb: Feature

#120 Feature/110 챌린지 모달 레이아웃
  src/components/Challenge/EndedChallengeCardList.tsx
Labels: :bulb: Feature, 👀 In review

#122 Feature/98 글 검색하기 배너 + 글 검색결과 배너
  src/components/Challenge/Banner/PieceSearchBanner.tsx
  src/components/Challenge/Banner/PieceSearchResult.tsx
  src/pages/Piece.tsx
Labels: :bulb: Feature, 👀 In review

#126 Feature/102 text length
  src/components/Challenge/Banner/ChallengeOfferInput.tsx
  src/components/Form/Textarea.tsx
  src/pages/ChallengeOffer.tsx
Labels: :bulb: Feature, 👀 In review

#129 feat: 알림 키워드 설정 모달
  src/components/Challenge/Card/NoticKeyword.tsx
  src/components/Modal/NoticeKeywordModal.tsx
Labels: :bulb: Feature, 👀 In review

#144 [챌린지] 제안 api 연결
  src/apis/challengeSuggestionAPI.ts
  src/components/Challenge/AllChallengeOfferList.tsx
  src/components/Challenge/Banner/AllChallengeOffer.tsx
  src/components/Challenge/Banner/ChallengeOfferInput.tsx
  src/components/Form/Textarea.tsx
  src/components/Form/index.ts
  src/components/Modal/ChallengeConfirmModal.tsx
  src/components/Peace/Post/CommentInput.tsx
  src/components/common/FlexButton.tsx
  src/constants/queryKeys.ts
  src/hooks/index.ts
  src/hooks/queries/challenge/suggestion/index.ts
  src/hooks/queries/challenge/suggestion/useAddChallengeSuggstion.ts
  src/hooks/queries/challenge/suggestion/useChallengeSuggestionListData.ts
  src/hooks/useTextArea.ts
  src/types/challengeSuggestion.ts
  src/types/index.ts
  src/types/user.ts
Labels: :bulb: Feature, 🤔 question

#147 feature: 라우트, 링크 연결, tos, privacy 페이지 추가
  src/App.tsx
  src/components/Footer/DesktopFooter.tsx
  src/components/Footer/MobileFooter.tsx
  src/pages/CrewIntro.tsx
  src/pages/Privacy.tsx
  src/pages/ServiceIntro.tsx
  src/pages/Tos.tsx
  src/pages/index.ts
Labels: :bulb: Feature, 👀 In review

#146 feature: 로그인 여부에 따라 navbar 다르게, 로그인/회원가입 페이지로 이동
  src/components/Navbar/DesktopNavbar.tsx
  src/pages/ChallengeOffer.tsx
  src/pages/Sign.tsx
Labels: :bulb: Feature

#155 Bug/131 route
  src/components/Navbar/DesktopNavbar.tsx
Labels: :bug: Bug, 👀 In review

#166 #157 챌린지 제안 페이지 레이아웃 조절
  src/components/Challenge/AllChallengeOfferList.tsx
  src/components/Challenge/Banner/AllChallengeOffer.tsx
  src/components/Challenge/Banner/ChallengeOfferInput.tsx
  src/components/Challenge/Card/ChallengeOfferCard.tsx
  src/layouts/maxWidth.layout.jsx
  src/layouts/mobile.layout.jsx
Labels: 👀 In review, 🧹 Refactor

#165 feat: 상점/포인트 이력 탭 컴포넌트
  src/components/Peace/Tab/Animal.tsx
  src/components/Peace/Tab/Island.tsx
  src/components/Peace/Tab/Item.tsx
  src/components/Peace/Tab/Point.tsx
  src/components/Peace/Tab/Tab.tsx
  src/components/Peace/Tab/index.ts
  src/components/common/FlexButton.tsx
  src/pages/Island.tsx
  yarn.lock
Labels: :bulb: Feature, 👀 In review

#172 bug: 로그인 페이지 이동 시 navbar 가 이상하게 남아있는 버그 수정
  src/components/Navbar/DesktopNavbar.tsx
Labels: :bug: Bug, 👀 In review

#171 Bug/138 모달 스크롤 시 쏠리는 버그 해결 + 반응형
  src/components/Form/Textarea.tsx
  src/components/Modal/ChallengeConfirmModal.tsx
  src/components/Modal/ModalFrame.tsx
  src/components/common/BannerBox.tsx
  src/components/common/FlexBox.tsx
  src/components/common/FlexTextBox.tsx
  src/components/common/Toggle.tsx
Labels: :bug: Bug, :bulb: Feature, 👏 Merge Needed

#170 Feature/non login
  src/components/Challenge/Banner/ChallengeOfferInput.tsx
  src/components/Challenge/Card/NoticKeyword.tsx
  src/components/Tooltip/Tooltip.tsx
  src/pages/Challenge.tsx
Labels: :bulb: Feature, 👏 Merge Needed

#173 Refactor/tab size
  src/components/Peace/Tab/Animal.tsx
  src/components/Peace/Tab/Island.tsx
  src/components/Peace/Tab/Item.tsx
  src/components/Peace/Tab/Point.tsx
  src/components/Peace/Tab/Tab.tsx
Labels: :bulb: Feature, 👀 In review

#175 피스 페이지 반응형 디자인
  src/components/Challenge/Banner/SimilarChallengeBanner.tsx
  src/components/Challenge/Card/ChallengeMiniCard.tsx
  src/components/Challenge/ChallengeBanner.tsx
  src/components/Challenge/SimilarChallengeList.tsx
  src/components/Peace/PieceSearchBanner.tsx
  src/components/Peace/Post/Comment.tsx
  src/components/Peace/Post/CommentContainer.tsx
  src/components/Peace/Post/CommentInput.tsx
  src/components/Peace/Post/Post.tsx
  src/components/Peace/Post/PostCard.tsx
  src/components/Peace/Post/PostCardList.tsx
  src/components/Peace/Post/PostContainer.tsx
  src/components/Peace/Writing.tsx
  src/components/common/FlexTextBox.tsx
  src/pages/Challenge.tsx
  src/pages/ChallengeSuggestion.tsx
  src/pages/Piece.tsx
  src/pages/PieceDetail.tsx
  src/pages/PieceSearch.tsx
  src/types/comment.ts
Labels: 🧹 Refactor

#181 feat: comment api 연결 (작성/읽기)
  package.json
  src/apis/articleCommentAPI.ts
  src/components/Challenge/Banner/PieceSearchResult.tsx
  src/components/Challenge/Card/TestimonialCard.tsx
  src/components/Peace/PieceSearchBanner.tsx
  src/components/Peace/Post/Comment.tsx
  src/components/Peace/Post/CommentContainer.tsx
  src/components/Peace/Post/CommentInput.tsx
  src/components/Peace/Post/Post.tsx
  src/components/Peace/Post/PostCard.tsx
  src/components/Peace/Post/dummyArticle.ts
  src/hooks/index.ts
  src/hooks/queries/article/comment/index.ts
  src/hooks/queries/article/comment/useAddComment.ts
  src/hooks/useDate.ts
  src/types/article.ts
  src/types/index.ts
  yarn.lock
Labels: :bulb: Feature, 👀 In review, 🧹 Refactor

#193 feat: article 작성
  src/components/Challenge/Banner/CertificationBanner.tsx
  src/components/Challenge/Banner/ChallengeDetailBanner.tsx
  src/components/Challenge/Banner/ChallengeSuggestionInput.tsx
  src/components/Challenge/Banner/ChallengeTestimonial.tsx
  src/components/Challenge/Card/ChallengeCard.tsx
  src/components/Challenge/Card/NoticKeyword.tsx
  src/components/Challenge/Card/TestimonialCard.tsx
  src/components/Challenge/ChallengeBanner.tsx
  src/components/Challenge/ChallengeTitle.tsx
  src/components/Challenge/TodayChallengeList.tsx
  src/components/Form/Textarea.tsx
  src/components/Modal/ChallengeConfirmModal.tsx
  src/components/Modal/CloseWarningModal.tsx
  src/components/Modal/ModalFrame.tsx
  src/components/Modal/ProfileModal.tsx
  src/components/Peace/Post/Comment.tsx
  src/components/Peace/Post/CommentContainer.tsx
  src/components/Peace/Post/CommentInput.tsx
  src/components/Peace/Post/Post.tsx
  src/components/Peace/Post/PostCardList.tsx
  src/components/Peace/Post/dummyCommemts.ts
  src/components/Peace/Writing.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/common/Toggle.tsx
  src/hooks/queries/article/useAddArticle.ts
  src/pages/ChallengeDetail.tsx
Labels: :bulb: Feature

#192 Refactor/177 모바일 navbar + 지난 챌린지 모바일 레이아웃
  src/components/Challenge/EndedChallengeCardList.tsx
  src/components/Challenge/TodayChallengeList.tsx
  src/components/Navbar/DesktopNavbar.tsx
  src/components/Navbar/MobileNavbar.tsx
  src/pages/EndedChallenge.tsx
Labels: :bulb: Feature, 👀 In review, 🧹 Refactor

#194 fix: 댓글 작성 후 value 초기화, 댓글 작성시 바로 보이지 않고 더보기로 보이는 현상 수정
  src/components/Peace/Post/CommentContainer.tsx
  src/components/Peace/Post/CommentInput.tsx
Labels: :bug: Bug

#205 Feature/101 crew intro page
  src/components/Challenge/Banner/ChallengeDetailBanner.tsx
  src/pages/CrewIntro.tsx
Labels: :bulb: Feature, 👀 In review

#206 feat: challenge suggestion feedback 연결
  src/apis/challengeSuggestionAPI.ts
  src/components/Challenge/Banner/ChallengeSuggestionGather.tsx
  src/components/Challenge/Card/ChallengeSuggestionCard.tsx
  src/config/queryClient.ts
  src/hooks/queries/article/useArticleListData.ts
  src/hooks/queries/article/useArticleSearchData.ts
  src/hooks/queries/challenge/reminder/useChallengeCategoryData.ts
  src/hooks/queries/challenge/suggestion/index.ts
  src/hooks/queries/challenge/suggestion/useAddSuggestionFeedback.ts
  src/hooks/queries/challenge/suggestion/useChallengeSuggestionListData.ts
  src/hooks/queries/challenge/suggestion/useDeleteSuggestionFeedback.ts
  src/hooks/queries/challenge/useChallengeArticleData.ts
  src/hooks/queries/challenge/useChallengeEndedData.ts
Labels: :bulb: Feature

#209 Feature/profile
  src/components/Modal/ProfileModal.tsx
  src/components/Navbar/DesktopNavbar.tsx
  src/components/Navbar/MobileNavbar.tsx
  src/components/common/Toggle.tsx
Labels: :bulb: Feature, 👀 In review

#212 feat: 비 로그인시 서비스소개 페이지로
  src/App.tsx
Labels: :bulb: Feature, 👀 In review

#210 Feature/176 인증글 반응형 모달 레이아웃
  src/components/Challenge/Banner/CertificationBanner.tsx
  src/components/Challenge/Banner/ChallengeTestimonial.tsx
  src/components/Modal/ChallengeConfirmModal.tsx
  src/components/Modal/ModalFrame.tsx
  src/components/Peace/Writing.tsx
  src/components/common/FlexButton.tsx
Labels: :bulb: Feature, 👀 In review

#216 feat: challenge reminder api 연결 / 리마인더 배너 및 모달 반응형 수정
  src/apis/articleCommentAPI.ts
  src/apis/challengeReminderAPI.ts
  src/components/Challenge/Banner/ChallengeSuggestionBanner.tsx
  src/components/Challenge/Card/NoticKeyword.tsx
  src/components/Challenge/TodayChallengeList.tsx
  src/components/Form/AutoComplete.tsx
  src/components/Modal/NoticeKeywordModal.tsx
  src/components/common/FlexButton.tsx
  src/constants/queryKeys.ts
  src/hooks/queries/article/comment/useAddComment.ts
  src/hooks/queries/challenge/reminder/index.ts
  src/hooks/queries/challenge/reminder/useAddChallengeReminder.ts
  src/hooks/queries/challenge/reminder/useChallengeCategoryData.ts
  src/hooks/queries/challenge/reminder/useChallengeReminderData.ts
  src/hooks/queries/challenge/reminder/useDeleteChallengeReminder.ts
  src/pages/Challenge.tsx
  src/types/index.ts
  src/types/reminder.ts
Labels: :bulb: Feature

#221 Bug/217 챌린지 상세페이지에서 종료된 챌린지 디자인 수정
  public/favicon.ico
  public/index.html
  src/components/Challenge/Banner/ChallengeDetailBanner.tsx
  src/components/Challenge/Banner/ChallengeTestimonial.tsx
  src/components/Modal/ModalFrame.tsx
  src/pages/ChallengeDetail.tsx
Labels: :bug: Bug, :bulb: Feature, 👀 In review

#228 Fix/footbar resposive
  public/images/logo.png
  src/components/Footer/DesktopFooter.tsx
  src/components/Footer/MobileFooter.tsx
  src/components/Navbar/DesktopNavbar.tsx
  src/components/Navbar/MobileNavbar.tsx
Labels: :bulb: Feature, 👀 In review

#224 Feature/알림창 툴팁 제작
  src/components/Navbar/DesktopNavbar.tsx
  src/components/Navbar/MobileNavbar.tsx
  src/components/Tooltip/NoticeTooltip/NoticeAll.tsx
  src/components/Tooltip/NoticeTooltip/NoticeNew.tsx
  src/components/Tooltip/NoticeTooltip/NoticeTab.tsx
  src/components/Tooltip/NoticeTooltip/NoticeTooltip.tsx
  src/components/Tooltip/NoticeTooltip/index.ts
  src/components/Tooltip/ProfileTooltip.tsx
  src/hooks/index.ts
  src/hooks/useDate.ts
Labels: :bulb: Feature, 👀 In review

#227 Feature/223 로딩 스피너
  src/components/Challenge/Banner/AllChallengeSuggestion.tsx
  src/components/Challenge/Banner/ChallengeTestimonial.tsx
  src/config/queryClient.ts
  src/index.tsx
  src/pages/Loading.tsx
  src/pages/PageLoading.tsx
  src/pages/Piece.tsx
  src/pages/PieceSearch.tsx
Labels: :bulb: Feature, 👀 In review

#244 feat: noti & usermenu
  src/apis/userAPI.ts
  src/components/Challenge/Banner/ChallengeSuggestionInput.tsx
  src/components/Form/Textarea.tsx
  src/components/Modal/ChallengeConfirmModal.tsx
  src/components/Navbar/DesktopNavbar.tsx
  src/components/Navbar/MobileNavbar.tsx
  src/components/Navbar/Noti/Noti.tsx
  src/components/Navbar/Noti/NotiList.tsx
  src/components/Navbar/Noti/NotiTab.tsx
  src/components/Navbar/Noti/index.ts
  src/components/Navbar/UserMenu.tsx
  src/components/Tooltip/NoticeTooltip/NoticeAll.tsx
  src/components/Tooltip/NoticeTooltip/NoticeNew.tsx
  src/components/Tooltip/NoticeTooltip/NoticeTab.tsx
  src/components/Tooltip/NoticeTooltip/index.ts
  src/components/Tooltip/ProfileTooltip.tsx
  src/components/common/Toggle.tsx
  src/config/queryClient.ts
  src/constants/queryKeys.ts
  src/hooks/queries/user/index.ts
  src/hooks/queries/user/useAddMailNoti.ts
  src/hooks/queries/user/useDeleteMailNoti.ts
  src/hooks/queries/user/useNotiData.ts
  src/hooks/queries/user/useReadNoti.ts
  src/hooks/queries/user/useReadNotiAll.ts
  src/hooks/useUser.ts
  src/index.tsx
  src/pages/ChallengeSuggestion.tsx
  src/types/index.ts
  src/types/noti.ts
Labels: :bulb: Feature

#250 fix: 링크 추가
  src/components/Footer/DesktopFooter.tsx
  src/components/Footer/MobileFooter.tsx
Labels: 🤔 question

#251 feat: 이모지 피드백 기능 추가
  .eslintrc.js
  package.json
  src/apis/articleAPI.js
  src/components/Peace/Feedback/Emoji.jsx
  src/components/Peace/Feedback/EmojiPicker.jsx
  src/components/Peace/Feedback/emoji-mart.locale.ko.json
  src/components/Peace/Post/Post.tsx
  src/hooks/queries/article/feedback/index.ts
  src/hooks/queries/article/feedback/useAddArticleFeedback.ts
  src/hooks/queries/article/feedback/useDeleteArticleFeedback.ts
  src/hooks/queries/article/index.ts
  src/hooks/queries/challenge/useRecommendChallengeData.ts
  src/styles/GlobalStyles.js
  src/types/article.ts
  src/types/feedback.ts
  src/types/index.ts
  yarn.lock
Labels: :bulb: Feature
